### ISSUE TITLE
separate identity proofing into 2 components?

### ISSUE THREAD

**Issue by leifj** [vectorsoftrust/strawman#3]
JB suggested that identity proofing is really two issues: 

1. Weather the subject is bound to a person in the legal sense (in the jurisdiction). This would be a boolean.
2. How well the subject is bound to the attributes associated with the subject

**Comment by jricher** [comment]
Current text covers (2) above, with (1) being a cross between a high value of (2) and a new "liability" category that could co-exist. 

We've also relaxed the wording around legal binding in the ID proofing component to avoid this confusion.
